spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate.SQL: TRACE
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 33001

management.port: -1

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop